---
- hosts: all
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: create index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: restart nginx
      service:
        name: nginx
        state: restarted
